from PIL import Image
import os.path

files = [("BOARD", "board.png"), ("BLACK_KING", "black-king.png")]

src = '#include "assets.h"\n\n/* File generated by assets/gen.py */\n\n'
header = '#ifndef ASSETS_H\n#define ASSETS_H\n#include "window.h"\n\n/* File generated by assets/gen.py */\n\n'

for varname, filename in files:
    filepath = os.path.join(os.path.dirname(__file__), filename)
    img = Image.open(filepath).convert(mode="RGBA")
    src += f"PixelImg {varname} = PixelImg({img.width}, {img.height}, {{"
    for j in range(img.height):
        if j != 0:
            src += ","
        src += "{"
        for i in range(img.width):
            if i != 0:
                src += ","
            r, g, b, a = img.getpixel((i, j))
            if a != 0:
                src += f"0x{r:02x}{g:02x}{b:02x}"
            else:
                src += "-1"
        src += "}"
    src += "});\n"
    header += f"extern PixelImg {varname};\n"
header += "\n#endif\n"

with open(os.path.join(os.path.dirname(__file__), "../src/assets.cc"), "w") as f:
    f.write(src)
with open(os.path.join(os.path.dirname(__file__), "../src/assets.h"), "w") as f:
    f.write(header)
