#ifndef ASSETS_H
#define ASSETS_H
#include "window.h"

/*
    Pixel image assets
    File generated by assets/gen.py
*/

extern PixelImg BOARD;
extern PixelImg BLACK_KING;
extern PixelImg WHITE_KING;
extern PixelImg BLACK_BISHOP;
extern PixelImg WHITE_BISHOP;
extern PixelImg BLACK_KNIGHT;
extern PixelImg WHITE_KNIGHT;
extern PixelImg BLACK_PAWN;
extern PixelImg WHITE_PAWN;
extern PixelImg BLACK_QUEEN;
extern PixelImg WHITE_QUEEN;
extern PixelImg BLACK_ROOK;
extern PixelImg WHITE_ROOK;
extern PixelImg ORANGE_SQUARE;
extern PixelImg YELLOW_SQUARE;
extern PixelImg TEXT_BLACK_CHECK;
extern PixelImg TEXT_BLACK_CHECKMATE;
extern PixelImg TEXT_BLACK_WINS;
extern PixelImg TEXT_WHITE_CHECK;
extern PixelImg TEXT_WHITE_CHECKMATE;
extern PixelImg TEXT_WHITE_WINS;
extern PixelImg TEXT_STALEMATE;

#endif
